# Generated by Django 4.1.1 on 2022-10-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplataform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplataform',
            name='about',
            field=models.CharField(max_length=150),
        ),
    ]
