# Generated by Django 4.1.1 on 2022-10-12 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_alter_streamplataform_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='plataform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist_app.streamplataform'),
            preserve_default=False,
        ),
    ]
