# Generated by Django 4.1.2 on 2022-10-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_revieww'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revieww',
            new_name='Review',
        ),
    ]
